cnt_epochs: 3
uncase: False
batch_size: 16
max_length: 128
model_name: "../transformers/configs/config_lsh_mlp-only.json"
# path_corpus: "./data/sense"
# path_val_corpus: "./data/sense_small"
path_corpus: "./tests/test_data/tokenized/sense/bert-base-uncased/128/"
# TODO: use same tokenized format for val
path_val_corpus: "./tests/test_data/sense/sense.txt"
path_results: ./lsh_run/
initial_lr: 1e-4
cnt_samples_per_epoch: 100
suffix: test
minutes_between_snapshots: 40
callbacks:
  monitor:
    working_directory: "../transformers/src/"
    module: transformers.models.lsh.callbacks
    class_name: AttachCallback
